# Generated by Django 5.2.2 on 2025-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobanko_app', '0002_customuser_delete_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
