# Generated by Django 5.2.2 on 2025-10-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobanko_app', '0003_alter_customuser_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
