# Generated by Django 5.2.2 on 2025-10-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobanko_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
