# Generated by Django 5.2.6 on 2025-10-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobanko_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
