# Generated by Django 5.2.2 on 2025-10-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobanko_app', '0006_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Perfil do usuário', 'verbose_name_plural': 'Perfis dos usuários'},
        ),
    ]
