# Generated by Django 5.2.2 on 2025-10-11 14:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobanko_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='transacao',
            name='contraparte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_como_contraparte', to='nobanko_app.cliente'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='saldo_resultante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='nobanko_app.cliente'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('processada_em', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='nobanko_app.cliente')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='nobanko_app.cliente')),
                ('transacao_destino', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_entrada', to='nobanko_app.transacao')),
                ('transacao_origem', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_saida', to='nobanko_app.transacao')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='nobanko_app.transferencia'),
        ),
    ]
