# Generated by Django 5.2.2 on 2025-11-06 16:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobanko_app', '0006_alter_transacao_options_transacao_contraparte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('limite_minimo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('limite_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['limite_minimo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartao',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_emitidos', to='nobanko_app.modelocartao'),
        ),
        migrations.CreateModel(
            name='PedidoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('cartao_emitido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origem', to='nobanko_app.cartao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cartao', to='nobanko_app.cliente')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cartao', to='nobanko_app.gerente')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='nobanko_app.modelocartao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], default='pendente', max_length=20)),
                ('resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_credito', to='nobanko_app.cliente')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_credito', to='nobanko_app.gerente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
